### ISSUE TITLE
com.microsoft.azure:azure-mobile-services-android-sdk:3.0-Beta can not resolved

### ISSUE THREAD

**Issue by ShreyashPromact** [Azure/azure-mobile-apps-android-client#11] opened 2015-12-16 10:27 UTC
Hello, I have just imported android client for Azure mobile apps. When i compile that, It gives me error like below:
Failed to resolve: com.microsoft.azure:azure-mobile-services-android-sdk:3.0-Beta

I guess the library is not available on maven repository. Not sure. 
Can you please help me compile that latest library. 

Sincerely,
Shreyash

**Comment by soninaren** [comment] 2015-12-16 20:49
@ShreyashPromact: 
We have changed the package name to compile 'com.microsoft.azure:azure-mobile-android:3.0'. Please update this line in the build.gradle file.

I tried to reproduce this by downloading Android client Azure mobile apps quick start. Where did you download / create the Azure mobile app from?

Thanks,
Naren

**Comment by ShreyashPromact** [comment] 2015-12-17 10:27
Yes, That's what I was talking about. Your document is not updated even with in your sample app "ZUMOAPPNAME", it is shown as 'com.microsoft.azure:azure-mobile-services-android-sdk:3.0-Beta' which is not compiling at all.

Some where I found to use below library for same and it is now working.
compile 'com.microsoft.azure:azure-mobile-android:3.0'
So, I suggest to update your sample app and document for same.

Thanks.

Sincerely,
Shreyash

**Comment by nvasilescu** [comment] 2015-12-22 15:46
I would have a problem because on gradle search you won't find it.

**Comment by ShreyashPromact** [comment] 2015-12-23 05:17
@nvasilescu 
I am able to compile both library version of Azure storage:
**compile 'com.microsoft.azure.android:azure-storage-android:0.5.1@aar'**
**compile 'com.microsoft.azure.android:azure-storage-android:0.7.0'**

If you are talking about Azure Mobile Service then try below link to get latest azure mobile service library. I guess you will not able to get it because it is not updated on Azure documentation.

**compile 'com.microsoft.azure:azure-mobile-android:3.0'**

I am able to compile and run it as well.

Sincerely,
Shreyash

**Comment by nvasilescu** [comment] 2015-12-24 12:44
I am not talking about the existence of this gradle library, but you can't find it on search.

if you search com.microsoft.azure on maven you won't find azure-mobile-android:3.0

**Comment by ShreyashPromact** [comment] 2015-12-25 05:49
@nvasilescu 
Yes, That's true. You will not able to get it from the maven search.
But just add dependency as below and compile the project. You will able to get it works fine.
compile 'com.microsoft.azure:azure-mobile-android:3.0'

Sincerely,
Shreyash

**Comment by mamaso** [comment] 2016-02-04 21:09
Resolved with this pr:
https://github.com/Azure/azure-mobile-apps-quickstarts/pull/26

**Closed by mamaso** 2016-02-04 21:09 UTC
